markdown: kramdown

highliter: rouge

permalink: /:categories/:title

name: wcec-home.org
url: http://wcec-home.org
media_url: http://media.wcec-home.org

paginate: 10

include: ['pages'] 
exclude: ['doc']

gems:
- jekyll-sitemap
